"""Pages package for AI-FitCoach."""
from pages.dashboard import render_dashboard_page
from pages.profile import render_profile_page
from pages.bmi_calculator import render_bmi_calculator_page
from pages.workout import render_workout_page
from pages.diet import render_diet_page
from pages.chatbot import render_chatbot_page
from pages.progress import render_progress_page
from pages.daily_tip import render_daily_tip_page
